### ISSUE TITLE
[docdb] Support tablet splitting + xcluster replication

### ISSUE THREAD

**Issue by hulien22** [yugabyte/yugabyte-db#10175]
Jira Link: [[DB-300]](https://yugabyte.atlassian.net/browse/DB-300)
Add support for handling tablet splitting in xcluster replication. 
The plan is to support independent split decisions on the producer/consumer sides, which means that we may need to also make some improvements to our M:N tablet mappings for xcluster.

---
**List of work items:**
- [x] Add support for splitting on the producer (#10874)
- [x] Ensure that parent tablet is not deleted until WAL has been read (#10296)
- [x] Add support for calling GetChanges on a tablet parent in CheckTabletValidForStream (#10296)
- [x] Support a tablet split occurring on the consumer (#10358)
- [x] Properly remove parent tablet + metadata + metrics (#12476)
- [x] Handle failures after split (#11030)
- [x] Add split children to cdc_state table and handle metrics for the new children tablets
- [x] Add support for switching from a 1-1 mapping to a M:N mapping
- [ ] Re-enable splitting by default for cdc enabled tables (see #8256)

---

**List of bug fixes:**
- [x] "Expected to find a write_request but were unable to" after delete operations with splitting (#11299)
- [x] #12164
---

**List of general improvements for M:N mappings:**
- [x] Improve the locality of pollers (#10186)
- [x] ~~Ability to see the producer->consumer tablet mapping~~ _(Already possible via get_universe_config)_
- [x] Ability to override CDCConsumerHandler threadpool size (#10211)
- [ ] Add metrics to track write locality for pollers
- [x] #8229

[DB-300]: https://yugabyte.atlassian.net/browse/DB-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by richiboi1977** [comment]
Here the thing I don't own a laptop or a tablet I own 2 phones one is android the other is iOS we

**Comment by hulien22** [comment]
Changes have been added to master and backported to 2.15.0 and 2.14
