### ISSUE TITLE
[YSQL] Improve performance for nested loop join execution 

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#14070]
Jira Link: [DB-3564](https://yugabyte.atlassian.net/browse/DB-3564)
### Description

Currently, we only support batched nested loop joins on a clause of the form `inner_table.c1 = outer_table.c1`. We can extend this support to
- [x] Conjoined simple clauses of the form `inner_table.c1 = outer_table.c1 AND inner_table.c2 = outer_table.c2`. (#14068)
- [x] Clauses with an expression on the outer variable of the form `inner_table.c1 = f(outer_table.c1)`. (#14069)
- [x] Fix readability of batched nested loop join explain output (#15366)
- [x] The fact that we silently recheck all our IN conditions at the YSQL level cuts away potential benefits from batching. (#13831)
- [x] RPCs with IN conditions on hash key tuples need to be batched (#7836)
- [x] Make the cost model aware of batching. (#14240)
- [ ] We can also look into supporting batching parameters that are fed into subplans. (#14071)
- [ ] Improve the performance of the TupleStore batching strategy. (#14393)

[DB-3564]: https://yugabyte.atlassian.net/browse/DB-3564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
