### ISSUE TITLE
[DocDB] Enhancements to memory management and tracking

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#16787]
Jira Link: [DB-6141](https://yugabyte.atlassian.net/browse/DB-6141)
### Description

This issue tracks the various memory management and tracking enhancements.

### Investigations
- [x] https://github.com/yugabyte/yugabyte-db/issues/16474
- [x] https://github.com/yugabyte/yugabyte-db/issues/16351
- [x] https://github.com/yugabyte/yugabyte-db/issues/12930
- [x] https://github.com/yugabyte/yugabyte-db/issues/14568
- [x] https://github.com/yugabyte/yugabyte-db/issues/13498

### Accounting
- [x] https://github.com/yugabyte/yugabyte-db/issues/17194
- [x] https://github.com/yugabyte/yugabyte-db/issues/17362
- [x] https://github.com/yugabyte/yugabyte-db/issues/17358
- [x] https://github.com/yugabyte/yugabyte-db/issues/17398
- [x] https://github.com/yugabyte/yugabyte-db/issues/17074
- [x] https://github.com/yugabyte/yugabyte-db/issues/13497
- [x] https://github.com/yugabyte/yugabyte-db/issues/4971
- [x] https://github.com/yugabyte/yugabyte-db/issues/6676
- [x] https://github.com/yugabyte/yugabyte-db/issues/16196
- [x] https://github.com/yugabyte/yugabyte-db/issues/17074
- [ ] https://github.com/yugabyte/yugabyte-db/issues/20164
- [ ] https://github.com/yugabyte/yugabyte-db/issues/19511
- [ ] https://github.com/yugabyte/yugabyte-db/issues/19073
- [ ] https://github.com/yugabyte/yugabyte-db/issues/3442
- [ ] https://github.com/yugabyte/yugabyte-db/issues/17222

### Visibility
- [x] https://github.com/yugabyte/yugabyte-db/issues/2433
- [x] https://github.com/yugabyte/yugabyte-db/issues/7271
- [ ] https://github.com/yugabyte/yugabyte-db/issues/17375
- [ ] https://github.com/yugabyte/yugabyte-db/issues/3353
- [ ] https://github.com/yugabyte/yugabyte-db/issues/18821
- [ ] https://github.com/yugabyte/yugabyte-db/issues/20501

### Limits and tuning
- [x] https://github.com/yugabyte/yugabyte-db/issues/7996
- [ ] https://github.com/yugabyte/yugabyte-db/issues/6331
- [ ] https://github.com/yugabyte/yugabyte-db/issues/13205
- [ ] https://github.com/yugabyte/yugabyte-db/issues/17151
- [ ] https://github.com/yugabyte/yugabyte-db/issues/17186
- [ ] https://github.com/yugabyte/yugabyte-db/issues/17187
- [ ] https://github.com/yugabyte/yugabyte-db/issues/17189
- [ ] https://github.com/yugabyte/yugabyte-db/issues/219

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-6141]: https://yugabyte.atlassian.net/browse/DB-6141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bmatican** [comment]
I think https://github.com/yugabyte/yugabyte-db/issues/6676 was a meta task, but there were several fixes to it for the rocksdb arena + per-table/tablet metrics from Rahul and Amit. We can probably close that out even.

Relatedly though, I'd love to see https://github.com/yugabyte/yugabyte-db/issues/16196 added sooner rather than later, as that is exactly the memory overhead that was improved upon previously, but it's currently NOT in the MemTracker. cc @rthallamko3
