### ISSUE TITLE
[DocDB] Speed up Analyze

### ISSUE THREAD

**Issue by rthallamko3** [yugabyte/yugabyte-db#22200]
Jira Link: [DB-11123](https://yugabyte.atlassian.net/browse/DB-11123)
### Description

Speed up Analyze.

**Problem**
As of 2024.1 release, YSQL analyze is implemented as a full table scan at the docdb layer, and the ysql layer filters away the rows that are necessary for the sample. This is expensive - For example, analyzing 100GB YSQL table can take several hours. 

**Suggestion**

Avoid scanning all the rows at the docdb layer, while still getting a good sample needed to setup the statistics.

Other ideas: 
- #15111
- #21656

**Sub-tasks**
- [x] #24112
- [x] #24113
- [x] https://github.com/yugabyte/yugabyte-db/issues/25858
- [x] https://github.com/yugabyte/yugabyte-db/issues/26455
- [x] https://github.com/yugabyte/yugabyte-db/issues/26366

### Issue Type

kind/enhancement

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11123]: https://yugabyte.atlassian.net/browse/DB-11123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
