### ISSUE TITLE
[DocDB] Vector Index Support

### ISSUE THREAD

**Issue by tanujnay112** [yugabyte/yugabyte-db#22828]
Jira Link: [DB-11727](https://yugabyte.atlassian.net/browse/DB-11727)
### Description

This issue tracks the effort for Vector Index Support in Yugabyte. Following are subtasks for this

- [x] #22195 : Add initial YSQL grammar for YB vector index type
- [x] #22825 : Add boilerplate read-path code for a dummy vector index implementation
- [x] #22826 : Enable ordered results from multi-tablet vector indexes
- [x] #22829: Push down LIMIT clause
- [x] #22827:  Make persistent vector indexes
- [x] #22898 : Sharding for vector indexes

### Issue Type

kind/new-feature

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-11727]: https://yugabyte.atlassian.net/browse/DB-11727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
