### ISSUE TITLE
[YSQL] Master issue of sql queries that need/can be optimized

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#3074]
Some are just optimizations, maybe they aren't needed ?

- [ ] n+1 queries for `generate_series` #2635
- [ ] slow count(*) #3055 #2946 
- [ ] slow `pg_depeng` query on `order_by` if index is picked when there's no `WHERE` https://github.com/yugabyte/yugabyte-db/issues/2959
- [ ] use index in `OR` `IN` filters #2898 
- [ ] skip postgres-ordering if query using sorted_primary_key https://github.com/yugabyte/yugabyte-db/issues/2792
- [ ] slow select after bulk_delete https://github.com/yugabyte/yugabyte-db/issues/1780
- [ ] reduce cost of un-prepared statements involving simple joins https://github.com/yugabyte/yugabyte-db/issues/1391
- [ ] push down `LIKE` operator https://github.com/yugabyte/yugabyte-db/issues/2970
- [ ] push down `regex` matching https://github.com/yugabyte/yugabyte-db/issues/2971
- [ ] push down `IN` #3130
- [ ] push down `OR` #3131 
- [ ] push down arithmetic operators https://github.com/yugabyte/yugabyte-db/issues/2969
- [ ] push down comparison operators https://github.com/yugabyte/yugabyte-db/issues/2968
- [ ] push down aggregates with `WHERE` clause https://github.com/yugabyte/yugabyte-db/issues/2931
- [ ] optimize `DELETE FROM table` https://github.com/yugabyte/yugabyte-db/issues/2930
- [ ] push down part of query plan to proxy server https://github.com/yugabyte/yugabyte-db/issues/2040
- [ ] investigate & speed-up scan performance https://github.com/yugabyte/yugabyte-db/issues/1789
- [ ] single-row optimization for valid returning expressions https://github.com/yugabyte/yugabyte-db/issues/2122
- [ ] do not query docdb when range column condition is `IN (NULL, NULL)` https://github.com/yugabyte/yugabyte-db/issues/2143
- [ ] temp table primary key does not use index scan  https://github.com/yugabyte/yugabyte-db/issues/2220
- [ ] Select on column used in partial index does not use the index https://github.com/yugabyte/yugabyte-db/issues/2275
- [ ] Batch FK trigger checks https://github.com/yugabyte/yugabyte-db/issues/2951
- [ ] batch selects https://github.com/yugabyte/yugabyte-db/issues/2960
- [ ] Columns with default values may be initialized to `null` instead https://github.com/yugabyte/yugabyte-db/issues/2021

@kmuthukk @ndeodhar @rkarthik007 @bmatican @nocaway

**Comment by ddorian** [comment]
moved to `slow sql queries` project https://github.com/yugabyte/yugabyte-db/projects/25
