### ISSUE TITLE
[docdb] Tracking issue: Get rid of the ent/ directory

### ISSUE THREAD

**Issue by bmatican** [yugabyte/yugabyte-db#5042]
Jira Link: [DB-1464](https://yugabyte.atlassian.net/browse/DB-1464)
Aside from still giving folks a bad impression that there's some enterprise only features, it also adds complexity to our code:
- need to support extra abstractions
- complicating git grep usage to figure out correct callsites
- increasing build times due to old cmake tricks we had to add

Components that will need to be moved
- [x] Load balancer (#8042)
- [x] Breakup CatalogManagerEnt file (#15954)
- [x] Backups (#16145)
- [x] Server (#16180)
- [x] 2DC / xCluster replication (#16220)
- [x] Tserver (#16251)
- [x] YbAdmin (#16266)
- [x] Master (#16330)
- [x] CatalogManager (#16331)
- [x]  Test Certs (#16332)
- [x] Build support and ent folder (#16400)

[DB-1464]: https://yugabyte.atlassian.net/browse/DB-1464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
