### ISSUE TITLE
[Master] Preflight checks for backup and encryption at-rest configuration

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6459]
Add pre-flight checks for backup and encryption at-rest configuration. In the case of validation failure, notify the user via the TASK window and disable backups for that configuration.  

- [x] [Platform] Preflight checks for S3 backup storage configuration #6857
- [x] [Platform] Preflight checks for NFS backup storage configuration #6858
- [ ] [Platform] Preflight checks for GCS backup storage configuration #6859
- [ ] [Platform] Preflight checks for Azure backup storage configuration #6860
- [ ] [Platform] Pre-flight checks for encryption-at-rest keys #6862

**Comment by streddy-yb** [comment]
For S3 Storage, when user initiates a manual backup -or- a scheduled backup, check whether S3 bucket is still accessible. This check can be performed on the platform side.

**Comment by chirag-yb** [comment]
@streddy-yb shouldn't the preflight check is done when AWS S3 configuration is added?

**Comment by jitendra-12113** [comment]
We added preflight checks for s3, GCS and encryption AT rest keys. 
For NFS, we can't have preflight checks at the time of creating the NFS storage, though we have this check to validate nFS path at the time of creating backup.

We don't have access to Azure so will wait untill we get the access. PFC for Azure backup storage configuration is pending.

Closing this for now. Please feel free to re-open when we had access to Azure. Thanks!
cc: @kkg-yb , @streddy-yb
