### ISSUE TITLE
[Master Task] - Improvements for K8s installation 

### ISSUE THREAD

**Issue by chirag-yb** [yugabyte/yugabyte-db#6669]
- [ ] Allow k8s univ creation to succeed even if no load balancer is set up [6267](https://github.com/yugabyte/yugabyte-db/issues/6267)
- [ ] Update prometheus config for platform to allow scraping data from multiple K8s clusters[6156](https://github.com/yugabyte/yugabyte-db/issues/6156)
- [ ] periodically cleanup core files in k8s deployments [6095](https://github.com/yugabyte/yugabyte-db/issues/6095)
- [ ] k8s universe upgrade does not wait for each pod to update before moving to the next [6360](https://github.com/yugabyte/yugabyte-db/issues/6360)
- [ ]Backup to GCS/Azure storage from a k8s universe does not work [6610](https://github.com/yugabyte/yugabyte-db/issues/6610)
- [ ] Connect button doesn't show correct connect string for k8s universe [6616](https://github.com/yugabyte/yugabyte-db/issues/6616)
- [ ] Add an init container to yugabyte helm charts to wait for container to be ready  [6019(https://github.com/yugabyte/yugabyte-db/issues/6019)
- [ ] Support platform backup [6668](https://github.com/yugabyte/yugabyte-db/issues/6668)
- [ ]  Disable start/stop nodes dropdowns in k8s [6084](https://github.com/yugabyte/yugabyte-db/issues/6084)
- [ ] Yugaware helm chart needs ability to reference alternate repositories [1634](https://github.com/yugabyte/yugabyte-db/issues/1634)
- [ ] YW k8s resource values cannot be overridden individually [5930](https://github.com/yugabyte/yugabyte-db/issues/5930)
- [ ] K8s Provider Config table view shows blank Config Path [6035](https://github.com/yugabyte/yugabyte-db/issues/6035)
